/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.JTableHeader;

/**
 *
 * @author KEVIN
 */
public class InventarioBodegaVista extends javax.swing.JFrame {

    /**
     * Creates new form InventarioBodegaVista
     */
    public InventarioBodegaVista() {
        initComponents();
        aplicarEstilosInventario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbBodega = new javax.swing.JComboBox<>();
        cmbLote = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("INVENTARIO DE BODEGA");

        jLabel2.setText("ID Bodega:");

        jLabel3.setText("ID Lote:");

        cmbBodega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbLote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoteActionPerformed(evt);
            }
        });

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BODEGA", "CODIGO", "PRODUCTO", "STOCK ACTUAL"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        btnBuscar.setText("BUSCAR");

        btnRegresar.setText("<");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addGap(100, 100, 100)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar)
                    .addComponent(lblTitulo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBuscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLoteActionPerformed

    public javax.swing.JComboBox<String> getCmbBodega() {
        return cmbBodega; 
    }
public javax.swing.JComboBox<String> getCmbLote() { 
    return cmbLote; 
} 

public javax.swing.JButton getBtnBuscar() {
    return btnBuscar; // Asegúrate de que coincida exactamente con la variable de tu botón
}

public javax.swing.JTable getTblInventario() {
    return tblInventario; 
}
    
public javax.swing.JButton getBtnRegresar() {
    return btnRegresar;
}

public javax.swing.table.DefaultTableModel getModeloTabla() {
    return (javax.swing.table.DefaultTableModel) tblInventario.getModel();
}

       public void cargarCombos(ArrayList<String> bodegas, ArrayList<String> lotes) {
    cmbBodega.removeAllItems();
    for (String b : bodegas) cmbBodega.addItem(b);

    cmbLote.removeAllItems();
    for (String l : lotes) cmbLote.addItem(l);
}
       
       public void aplicarEstilosInventario() {
    // 1. Colores y fuentes corporativas
    Color azulBodega = new Color(15, 23, 42);      // #0F172A (Azul marino industrial)
    Color azulAccion = new Color(37, 99, 235);     // #2563EB (Azul corporativo)
    Color textoGris = new Color(71, 85, 105);      // #475569
    Color grisLineas = new Color(226, 232, 240);   // #E2E8F0

    Font fuenteBase = new Font("Segoe UI", Font.PLAIN, 13);
    Font fuenteNegrita = new Font("Segoe UI", Font.BOLD, 13);
    Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 18);

    // 2. Título de la Vista
    lblTitulo.setText("INVENTARIO Y STOCK DE BODEGA");
    lblTitulo.setFont(fuenteTitulo);
    lblTitulo.setForeground(azulBodega);

    // 3. Botón Regresar y Etiquetas
    btnRegresar.setText("← Volver");
    btnRegresar.setFont(fuenteBase);

    if (cmbBodega != null) {
        cmbBodega.setFont(fuenteNegrita);
        cmbBodega.setForeground(textoGris);
    }
    if (cmbLote != null) {
        cmbLote.setFont(fuenteNegrita);
        cmbLote.setForeground(textoGris);
    }

    // 4. Botón Buscar
    btnBuscar.setText("BUSCAR STOCK");
    btnBuscar.setBackground(azulAccion);
    btnBuscar.setForeground(Color.WHITE);
    btnBuscar.setFont(fuenteNegrita);
    btnBuscar.setOpaque(true);
    btnBuscar.setBorderPainted(false);
    btnBuscar.setFocusPainted(false);
    btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // 5. Estilizar Tabla de Stock (JTable)
    if (tblInventario != null) {
        JTableHeader header = tblInventario.getTableHeader();
        header.setBackground(azulBodega);
        header.setForeground(Color.WHITE);
        header.setFont(fuenteNegrita);
        header.setPreferredSize(new Dimension(header.getWidth(), 35));

        tblInventario.setRowHeight(28);
        tblInventario.setFont(fuenteBase);
        tblInventario.setGridColor(grisLineas);
        tblInventario.setShowVerticalLines(false);
        tblInventario.setSelectionBackground(new Color(219, 234, 254)); // Azul claro al seleccionar fila
        tblInventario.setSelectionForeground(Color.BLACK);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioBodegaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioBodegaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioBodegaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioBodegaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioBodegaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbBodega;
    private javax.swing.JComboBox<String> cmbLote;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables
}
