/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author KEVIN
 */
public class LoteVista extends javax.swing.JFrame {

    /**
     * Creates new form LoteVista
     */
    public LoteVista() {
        initComponents();
        aplicarEstilosLotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblCodigoLote = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        txtCodigoLote = new javax.swing.JTextField();
        lblFechaVencimiento = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        cbxBodega = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JLabel();
        lblProducto = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");

        btnEditar.setText("Editar");

        btnBuscar.setText("Buscar");

        btnDeshabilitar.setText("Deshabilitar");

        lblTitulo.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 255));
        lblTitulo.setText("REGISTRO DE LOTE");

        lblCodigoLote.setText("Codigo Lote:");

        lblDescripcion.setText("ID Bodega:");

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Lote", "Ubicación", "Fecha Vencimiento", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblLotes);

        lblFechaVencimiento.setText("Fecha Vencimiento:");

        txtFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVencimientoActionPerformed(evt);
            }
        });

        cbxBodega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegresar.setText("<");

        btnPDF.setText("PDF");

        jLabel1.setText("Producto:");

        txtCantidad.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(84, 84, 84)
                        .addComponent(btnEditar)
                        .addGap(58, 58, 58)
                        .addComponent(btnDeshabilitar)
                        .addGap(30, 30, 30))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addGap(93, 93, 93)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(btnPDF))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCodigoLote, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(lblFechaVencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtCantidad)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoLote, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txtFechaVencimiento)
                                    .addComponent(cbxBodega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProducto)
                                    .addComponent(lblCantidad))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTitulo)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoLote)
                    .addComponent(txtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(cbxBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar)
                    .addComponent(btnBuscar)
                    .addComponent(btnDeshabilitar))
                .addGap(35, 35, 35)
                .addComponent(btnPDF))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVencimientoActionPerformed
public DefaultTableModel getModeloTabla() {
    return (DefaultTableModel) tblLotes.getModel();
}

    public int getFilaSeleccionada() {
        return tblLotes.getSelectedRow();
    }
    
    
    public String getCodigoLote() { 
        return txtCodigoLote.getText().trim();
    }
    
    
    public String getFechaVencimiento() { 
        return txtFechaVencimiento.getText().trim(); 
    }
    
    public JComboBox<String> getCbxBodega() {
        return cbxBodega; 
    }

    public void setCodigoLote(String texto) {
        txtCodigoLote.setText(texto); 
    }
    
    public void setFechaVencimiento(String texto) {
        txtFechaVencimiento.setText(texto); 
    }

    public JTextField getTxtCodigoLote() {
        return txtCodigoLote; 
    }
    
    public JTextField getTxtFechaVencimiento() {
        return txtFechaVencimiento; 
    }
    
    public JTextField getLblProductoInf() { 
        return lblProducto; 
    }
    
    public JTextField getLblCantidadInf() {
        return lblCantidad; 
    }
    
    public JTable getTblLotes() { 
        return tblLotes; 
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }
    
    public JButton getBtnBuscar() {
        return btnBuscar; 
    }
    
    public JButton getBtnEditar() {
        return btnEditar;
    }
    
    public JButton getBtnDeshabilitar() {
        return btnDeshabilitar; 
    }
    
    public JButton getBtnRegresar() {
        return btnRegresar; 
    }
    
    public JButton getBtnPDF() { 
        return btnPDF; 
    }

 

    public void addGuardarListener(ActionListener l) { 
        btnGuardar.addActionListener(l);
    }
    public void addEditarListener(ActionListener l) {
        btnEditar.addActionListener(l); 
    }
    
    public void addDeshabilitarListener(ActionListener l) {
        btnDeshabilitar.addActionListener(l); 
    }
    public void addBuscarListener(ActionListener l) {
        btnBuscar.addActionListener(l); 
    }
    
    public void addRegresarListener(ActionListener l) {
        btnRegresar.addActionListener(l); 
    }
    
    public void addPDFListener(ActionListener l) {
        btnPDF.addActionListener(l);
    }
    public void addTablaListener(MouseAdapter adapter) { 
        tblLotes.addMouseListener(adapter);
    }

 public String getTxtCantidadText() {
    return lblCantidad.getText().trim();
}

public JTextField getTxtCantidad() {
    return lblCantidad;
}

public String getProductoText() {
    return lblProducto.getText().trim();
}

    public void aplicarEstilosLotes() {
        Color azulBodega = new Color(15, 23, 42);
        Color azulAccion = new Color(37, 99, 235);
        Color verdeAccion = new Color(16, 185, 129);
        Color rojoPeligro = new Color(220, 38, 38);
        Color grisBoton = new Color(100, 116, 139);
        Color grisLineas = new Color(226, 232, 240);

        Font fuenteBase = new Font("Segoe UI", Font.PLAIN, 13);
        Font fuenteNegrita = new Font("Segoe UI", Font.BOLD, 13);
        Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 18);

        if (lblTitulo != null) {
            lblTitulo.setText("REGISTRO Y CONTROL DE LOTES");
            lblTitulo.setFont(fuenteTitulo);
            lblTitulo.setForeground(azulBodega);
        }

        if (btnRegresar != null) {
            btnRegresar.setText("← Volver");
            btnRegresar.setFont(fuenteBase);
        }

        estilarBoton(btnBuscar, "BUSCAR", grisBoton, fuenteNegrita);
        estilarBoton(btnGuardar, "GUARDAR LOTE", azulAccion, fuenteNegrita);
        estilarBoton(btnEditar, "EDITAR", verdeAccion, fuenteNegrita);
        estilarBoton(btnDeshabilitar, "DESHABILITAR", rojoPeligro, fuenteNegrita);
        estilarBoton(btnPDF, "GENERAR PDF", azulBodega, fuenteNegrita);

        if (tblLotes != null) {
            JTableHeader header = tblLotes.getTableHeader();
            header.setBackground(azulBodega);
            header.setForeground(Color.WHITE);
            header.setFont(fuenteNegrita);
            header.setPreferredSize(new Dimension(header.getWidth(), 35));

            tblLotes.setRowHeight(28);
            tblLotes.setFont(fuenteBase);
            tblLotes.setGridColor(grisLineas);
            tblLotes.setShowVerticalLines(false);
            tblLotes.setSelectionBackground(new Color(219, 234, 254));
            tblLotes.setSelectionForeground(Color.BLACK);
        }
    }

    private void estilarBoton(JButton btn, String texto, Color bg, Font fuente) {
        if (btn != null) {
            btn.setText(texto);
            btn.setBackground(bg);
            btn.setForeground(Color.WHITE);
            btn.setFont(fuente);
            btn.setOpaque(true);
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxBodega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblCantidad;
    private javax.swing.JLabel lblCodigoLote;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JTextField lblProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblLotes;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JTextField txtCodigoLote;
    private javax.swing.JTextField txtFechaVencimiento;
    // End of variables declaration//GEN-END:variables
}
