/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author KEVIN
 */
public class LoteVista extends javax.swing.JFrame {

    /**
     * Creates new form LoteVista
     */
    public LoteVista() {
        initComponents();
        aplicarEstilosLotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblCodigoLote = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        txtCodigoLote = new javax.swing.JTextField();
        lblFechaVencimiento = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        cbxBodega = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        btnCrearProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");

        btnEditar.setText("Editar");

        btnBuscar.setText("Buscar");

        btnDeshabilitar.setText("Deshabilitar");

        lblTitulo.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 255));
        lblTitulo.setText("REGISTRO DE LOTE");

        lblCodigoLote.setText("Codigo Lote:");

        lblDescripcion.setText("ID Bodega:");

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Lote", "Ubicación", "Fecha Vencimiento", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblLotes);

        lblFechaVencimiento.setText("Fecha Vencimiento:");

        txtFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVencimientoActionPerformed(evt);
            }
        });

        cbxBodega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegresar.setText("<");

        btnCrearProducto.setText("Crear Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(84, 84, 84)
                .addComponent(btnEditar)
                .addGap(58, 58, 58)
                .addComponent(btnDeshabilitar)
                .addGap(30, 30, 30))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(93, 93, 93)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodigoLote, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblFechaVencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoLote, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtFechaVencimiento)
                            .addComponent(cbxBodega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnCrearProducto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTitulo)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoLote)
                    .addComponent(txtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(cbxBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar)
                    .addComponent(btnBuscar)
                    .addComponent(btnDeshabilitar))
                .addGap(53, 53, 53)
                .addComponent(btnCrearProducto)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVencimientoActionPerformed
public DefaultTableModel getModeloTabla() {
        return (DefaultTableModel) tblLotes.getModel(); 
    }

    
    public int getFilaSeleccionada() {
        return tblLotes.getSelectedRow(); 
    }

    public String getCodigoLote() {
        return txtCodigoLote.getText(); 
    }

   

    public String getFechaVencimiento() {
        return txtFechaVencimiento.getText(); 
    }

   
   

public JComboBox<String> getCbxBodega() {
    return cbxBodega; }
   
    public void setCodigoLote(String texto) {
        txtCodigoLote.setText(texto);
    }

   

    public void setFechaVencimiento(String texto) {
        txtFechaVencimiento.setText(texto);
    }




    public void addGuardarListener(ActionListener l) {
        btnGuardar.addActionListener(l); 
    }

    public void addEditarListener(ActionListener l) {
        btnEditar.addActionListener(l);
    }

    public void addDeshabilitarListener(ActionListener l) {
        btnDeshabilitar.addActionListener(l);
    }

    public void addBuscarListener(ActionListener l) {
        btnBuscar.addActionListener(l);
    }

    public void addTablaListener(MouseAdapter adapter) {
        tblLotes.addMouseListener(adapter);
    }
    
    public javax.swing.JButton getBtnRegresar() {
    return btnRegresar; 
}
    
    public javax.swing.JButton getBtnCrearProducto() {
    return btnCrearProducto;
    
}
    public javax.swing.JTextField getTxtCodigoLote() {
    return txtCodigoLote; // Reemplaza "txtCodigoLote" por el nombre exacto de tu JTextField si es distinto (ej. txtCodigo, txtLote)
}

public javax.swing.JTextField getTxtFechaVencimiento() {
    return txtFechaVencimiento; // Reemplaza por el nombre exacto de tu componente de fecha
}
    public javax.swing.JTable getTblLotes() {
    return tblLotes; // Cambia 'tblLotes' por el nombre exacto de la variable de tu JTable si difiere (ej. jTable1, tablaLotes)
}
    
    
    public void aplicarEstilosLotes() {
    // 1. Colores y fuentes del ecosistema de logística
    Color azulBodega = new Color(15, 23, 42);      // #0F172A (Azul marino industrial)
    Color azulAccion = new Color(37, 99, 235);     // #2563EB (Azul primario para Guardar/Crear)
    Color verdeAccion = new Color(16, 185, 129);   // #10B981 (Verde esmeralda para Editar)
    Color rojoPeligro = new Color(220, 38, 38);    // #DC2626 (Rojo advertencia para Deshabilitar)
    Color grisBoton = new Color(100, 116, 139);    // #64748B (Gris neutro para Buscar)
    Color grisLineas = new Color(226, 232, 240);   // #E2E8F0

    Font fuenteBase = new Font("Segoe UI", Font.PLAIN, 13);
    Font fuenteNegrita = new Font("Segoe UI", Font.BOLD, 13);
    Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 18);

    // 2. Título de la Vista y Botón Regresar
    if (lblTitulo != null) {
        lblTitulo.setText("REGISTRO Y CONTROL DE LOTES");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setForeground(azulBodega);
    }
    
    btnRegresar.setText("← Volver");
    btnRegresar.setFont(fuenteBase);

    // 3. Estilizar Botones de Operación
    // Botón Buscar (Gris Neutro)
    btnBuscar.setText("BUSCAR");
    btnBuscar.setBackground(grisBoton);
    btnBuscar.setForeground(Color.WHITE);
    btnBuscar.setFont(fuenteNegrita);
    btnBuscar.setOpaque(true);
    btnBuscar.setBorderPainted(false);
    btnBuscar.setFocusPainted(false);

    // Botón Guardar (Azul Corporativo)
    btnGuardar.setText("GUARDAR");
    btnGuardar.setBackground(azulAccion);
    btnGuardar.setForeground(Color.WHITE);
    btnGuardar.setFont(fuenteNegrita);
    btnGuardar.setOpaque(true);
    btnGuardar.setBorderPainted(false);
    btnGuardar.setFocusPainted(false);

    // Botón Editar (Verde Operativo)
    btnEditar.setText("EDITAR");
    btnEditar.setBackground(verdeAccion);
    btnEditar.setForeground(Color.WHITE);
    btnEditar.setFont(fuenteNegrita);
    btnEditar.setOpaque(true);
    btnEditar.setBorderPainted(false);
    btnEditar.setFocusPainted(false);

    // Botón Deshabilitar (Rojo Advertencia)
    btnDeshabilitar.setText("DESHABILITAR");
    btnDeshabilitar.setBackground(rojoPeligro);
    btnDeshabilitar.setForeground(Color.WHITE);
    btnDeshabilitar.setFont(fuenteNegrita);
    btnDeshabilitar.setOpaque(true);
    btnDeshabilitar.setBorderPainted(false);
    btnDeshabilitar.setFocusPainted(false);

    // Botón Crear Producto (Azul Principal)
    if (btnCrearProducto != null) {
        btnCrearProducto.setText("CREAR PRODUCTO");
        btnCrearProducto.setBackground(azulBodega);
        btnCrearProducto.setForeground(Color.WHITE);
        btnCrearProducto.setFont(fuenteNegrita);
        btnCrearProducto.setOpaque(true);
        btnCrearProducto.setBorderPainted(false);
        btnCrearProducto.setFocusPainted(false);
    }

    // 4. Estilizar Tabla (JTable)
    if (tblLotes != null) {
        JTableHeader header = tblLotes.getTableHeader();
        header.setBackground(azulBodega);
        header.setForeground(Color.WHITE);
        header.setFont(fuenteNegrita);
        header.setPreferredSize(new Dimension(header.getWidth(), 35));

        tblLotes.setRowHeight(28);
        tblLotes.setFont(fuenteBase);
        tblLotes.setGridColor(grisLineas);
        tblLotes.setShowVerticalLines(false);
        tblLotes.setSelectionBackground(new Color(219, 234, 254));
        tblLotes.setSelectionForeground(Color.BLACK);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxBodega;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoLote;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txtCodigoLote;
    private javax.swing.JTextField txtFechaVencimiento;
    // End of variables declaration//GEN-END:variables
}
