/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author KEVIN
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdministrarUsuarios = new javax.swing.JButton();
        btnGestionLotesProductos = new javax.swing.JButton();
        btnInventarioBodegas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENÚ ADMNISTRADOR ");

        btnAdministrarUsuarios.setText("ADMINISTRAR USUARIOS");
        btnAdministrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarUsuariosActionPerformed(evt);
            }
        });

        btnGestionLotesProductos.setText("GESTION DE LOTES Y PRODUCTOS");
        btnGestionLotesProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLotesProductosActionPerformed(evt);
            }
        });

        btnInventarioBodegas.setText("INVENTARIO BODEGAS ");

        btnCerrarSesion.setText("CERRAR SESIÓN ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGestionLotesProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInventarioBodegas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdministrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnAdministrarUsuarios)
                .addGap(30, 30, 30)
                .addComponent(btnGestionLotesProductos)
                .addGap(34, 34, 34)
                .addComponent(btnInventarioBodegas)
                .addGap(29, 29, 29)
                .addComponent(btnCerrarSesion)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarUsuariosActionPerformed

    private void btnGestionLotesProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLotesProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionLotesProductosActionPerformed

    public javax.swing.JButton getBtnAdministrarUsuarios() {
    return btnAdministrarUsuarios; // Reemplaza por el nombre variable de tu botón
}

public javax.swing.JButton getBtnGestionLotesProductos() {
    return btnGestionLotesProductos; // Reemplaza por el nombre variable de tu botón
}

public javax.swing.JButton getBtnInventarioBodegas() {
    return btnInventarioBodegas; // Reemplaza por el nombre variable de tu botón
}
    

private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                
    // 1. Limpiar o destruir datos de la sesión actual si usas una clase SesionUsuario
    // SesionUsuario.limpiarSesion(); 

    // 2. Instanciar la vista de Login (asumiendo que se llama LoginVista o Login)
    InicioSesion vistaLogin = new InicioSesion(); 
    vistaLogin.setVisible(true);
    vistaLogin.setLocationRelativeTo(null); // Centrar en pantalla

    // 3. Cerrar la ventana actual del Menú Administrador
    this.dispose(); 
}

public javax.swing.JButton getBtnCerrarSesion() {
    return btnCerrarSesion; // Cambia "btnCerrarSesion" si le pusiste otro nombre a la variable en el Designer
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarUsuarios;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionLotesProductos;
    private javax.swing.JButton btnInventarioBodegas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
