/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;

/**
 *
 * @author KEVIN
 */
public class MenuBodeguero extends javax.swing.JFrame {

    /**
     * Creates new form MenuBodeguero
     */
    public MenuBodeguero() {
        initComponents();
        aplicarEstilosMenuBodeguero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienVenido = new javax.swing.JLabel();
        btnSalidaProductos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnInventarioBodega = new javax.swing.JButton();
        btnEntradaProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienVenido.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        lblBienVenido.setText("Bienvenido al sistema de logistica XYZ");

        btnSalidaProductos.setText("SALIDA DE PRODUCTOS");
        btnSalidaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaProductosActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("CERRAR SESIÓN ");

        btnInventarioBodega.setText("INVENTARIO BODEGAS ");

        btnEntradaProductos.setText("ENTRADA DE PRODUCTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblBienVenido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalidaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInventarioBodega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEntradaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 196, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBienVenido)
                .addGap(50, 50, 50)
                .addComponent(btnEntradaProductos)
                .addGap(38, 38, 38)
                .addComponent(btnSalidaProductos)
                .addGap(35, 35, 35)
                .addComponent(btnInventarioBodega)
                .addGap(39, 39, 39)
                .addComponent(btnCerrarSesion)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaProductosActionPerformed

// --- GETTERS PARA EL CONTROLADOR (MenuBodegueroControlador) ---
    public javax.swing.JButton getBtnEntradaProductos() {
        return btnEntradaProductos;
    }

    public javax.swing.JButton getBtnMovimientoAlmacen() {
        return btnSalidaProductos;
    }
    
    public javax.swing.JButton getBtnInventarioBodega() {
        return btnInventarioBodega;
    }

    public javax.swing.JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    // --- ESTILOS VISUALES ---
    public void aplicarEstilosMenuBodeguero() {
        Color azulOscuro = new Color(15, 23, 42);      // #0F172A
        Color azulBoton = new Color(30, 58, 138);      // #1E3A8A
        Color rojoCerrar = new Color(220, 38, 38);     // #DC2626

        Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 20);
        Font fuenteBoton = new Font("Segoe UI", Font.BOLD, 13);

        if (lblBienVenido != null) {
            lblBienVenido.setText("BIENVENIDO AL SISTEMA DE LOGÍSTICA");
            lblBienVenido.setFont(fuenteTitulo);
            lblBienVenido.setForeground(azulOscuro);
        }

        JButton[] botonesOperacion = {btnEntradaProductos, btnSalidaProductos, btnInventarioBodega};
        
        for (JButton btn : botonesOperacion) {
            if (btn != null) {
                btn.setBackground(azulBoton);
                btn.setForeground(Color.WHITE);
                btn.setFont(fuenteBoton);
                btn.setOpaque(true);
                btn.setBorderPainted(false);
                btn.setFocusPainted(false);
                btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        }

        if (btnCerrarSesion != null) {
            btnCerrarSesion.setText("CERRAR SESIÓN");
            btnCerrarSesion.setBackground(rojoCerrar);
            btnCerrarSesion.setForeground(Color.WHITE);
            btnCerrarSesion.setFont(fuenteBoton);
            btnCerrarSesion.setOpaque(true);
            btnCerrarSesion.setBorderPainted(false);
            btnCerrarSesion.setFocusPainted(false);
            btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBodeguero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBodeguero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBodeguero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBodeguero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBodeguero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEntradaProductos;
    private javax.swing.JButton btnInventarioBodega;
    private javax.swing.JButton btnSalidaProductos;
    private javax.swing.JLabel lblBienVenido;
    // End of variables declaration//GEN-END:variables
}
