/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author KEVIN
 */
public class MovimientoAlmacenVista extends javax.swing.JFrame {

    /**
     * Creates new form MovimientoAlmacenVista
     */
    public MovimientoAlmacenVista() {
        initComponents();
        aplicarEstilosMovimientoAlmacen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBodegaOrigen = new javax.swing.JLabel();
        lblBodegaDestino = new javax.swing.JLabel();
        cmbTipoMovimiento = new javax.swing.JComboBox<>();
        cmbBodegaOrigen = new javax.swing.JComboBox<>();
        lblObservacion = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        lblTipoMovimiento = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        cmbBodegaDestino = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo Movimiento");

        lblTitulo.setText("SOLICITUD MOVIMIENTO DE ALMACEN ");

        lblBodegaOrigen.setText("Bodega de Origen:");

        lblBodegaDestino.setText("Bodega Destino:");

        cmbTipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRADA DE PRODUCTO", "SALIDA DE PRODUCTO" }));
        cmbTipoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoMovimientoActionPerformed(evt);
            }
        });

        cmbBodegaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblObservacion.setText("Observación:");

        txtObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionActionPerformed(evt);
            }
        });

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TIPO DE MOVIMIENTO", "BODEGA DE ORIGEN", "BODEGA DE DESTINO", "RESPONSABLE", "OBSERVACIÓN", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(tblMovimientos);

        lblTipoMovimiento.setText("Tipo Movimiento:");

        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        cmbBodegaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegresar.setText("<");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblBodegaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoMovimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBodegaDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblTipoMovimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(287, 287, 287)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBodegaOrigen)
                    .addComponent(lblObservacion))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBodegaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipoMovimiento)
                        .addComponent(cmbTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBodegaOrigen)
                        .addComponent(cmbBodegaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBodegaDestino)
                    .addComponent(lblObservacion)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBodegaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoMovimientoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionActionPerformed

    
    public javax.swing.JComboBox getCmbTipoMovimiento() {
    return cmbTipoMovimiento;
}

public javax.swing.JComboBox getCmbBodegaOrigen() {
    return cmbBodegaOrigen;
}

public javax.swing.JComboBox getCmbBodegaDestino() {
    return cmbBodegaDestino;
}

public javax.swing.JTextField getTxtObservacion() {
    return txtObservacion;
}

public javax.swing.JButton getBtnGenerar() {
    return btnGenerar;
}

public javax.swing.JTable getTblMovimientos() {
    return tblMovimientos;
}

public javax.swing.JButton getBtnRegresar() {
    return btnRegresar; 
}
    


public void aplicarEstilosMovimientoAlmacen() {
    // 1. Colores y fuentes de la línea gráfica
    Color azulBodega = new Color(15, 23, 42);      // #0F172A (Encabezados y títulos)
    Color azulAccion = new Color(37, 99, 235);     // #2563EB (Azul corporativo)
    Color textoGris = new Color(71, 85, 105);      // #475569
    Color grisLineas = new Color(226, 232, 240);   // #E2E8F0

    Font fuenteBase = new Font("Segoe UI", Font.PLAIN, 13);
    Font fuenteNegrita = new Font("Segoe UI", Font.BOLD, 13);
    Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 18);

    // 2. Título Principal y Botón Regresar
    if (lblTitulo != null) {
        lblTitulo.setText("SOLICITUD MOVIMIENTO DE ALMACÉN");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setForeground(azulBodega);
    }
    
    if (btnRegresar != null) {
        btnRegresar.setText("← Volver");
        btnRegresar.setFont(fuenteBase);
    }

    // 3. Estilo de Etiquetas (Labels)
    JLabel[] etiquetas = {lblTipoMovimiento, lblBodegaOrigen, lblBodegaDestino, lblObservacion};
    for (JLabel lbl : etiquetas) {
        if (lbl != null) {
            lbl.setFont(fuenteNegrita);
            lbl.setForeground(textoGris);
        }
    }

    // 4. Botón Generar (Acción Principal)
    if (btnGenerar != null) {
        btnGenerar.setText("GENERAR MOVIMIENTO");
        btnGenerar.setBackground(azulAccion);
        btnGenerar.setForeground(Color.WHITE);
        btnGenerar.setFont(fuenteNegrita);
        btnGenerar.setOpaque(true);
        btnGenerar.setBorderPainted(false);
        btnGenerar.setFocusPainted(false);
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    // 5. Estilizar Tabla (JTable)
    if (tblMovimientos != null) {
        JTableHeader header = tblMovimientos.getTableHeader();
        header.setBackground(azulBodega);
        header.setForeground(Color.WHITE);
        header.setFont(fuenteNegrita);
        header.setPreferredSize(new Dimension(header.getWidth(), 35));

        tblMovimientos.setRowHeight(28);
        tblMovimientos.setFont(fuenteBase);
        tblMovimientos.setGridColor(grisLineas);
        tblMovimientos.setShowVerticalLines(false);
        tblMovimientos.setSelectionBackground(new Color(219, 234, 254));
        tblMovimientos.setSelectionForeground(Color.BLACK);
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientoAlmacenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientoAlmacenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientoAlmacenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientoAlmacenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientoAlmacenVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbBodegaDestino;
    private javax.swing.JComboBox<String> cmbBodegaOrigen;
    private javax.swing.JComboBox<String> cmbTipoMovimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBodegaDestino;
    private javax.swing.JLabel lblBodegaOrigen;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblTipoMovimiento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtObservacion;
    // End of variables declaration//GEN-END:variables
}
